### ISSUE TITLE
Materias inactivas

### ISSUE THREAD

**Issue by frankete333** [cedarcode/mi_carrera#379]
No estoy seguro como categorizan una materia como inactiva o activa, si es un proceso manual o viene como parte de la data con el scraper, pero por ejemplo note que `2415 - Codigos Para Correccion De Errores` esta como inactiva cuando se esta dictando este semestre.
[Link Eva](https://eva.fing.edu.uy/course/view.php?id=134)
<img width="1414" alt="image" src="https://github.com/cedarcode/mi_carrera/assets/36253280/b31051c0-4814-4038-9232-861b1a23f10f">

**Comment by RenzoMinelli** [comment]
Si por ahora es un proceso manual, usamos el archivo [subject_overrides.yml](https://github.com/cedarcode/mi_carrera/blob/master/db/data/subject_overrides.yml) para setear esas cosas. Las categorias están definidas en el [modelo de subject](https://github.com/cedarcode/mi_carrera/blob/master/app/models/subject.rb#L13-L28). 

En el archivo [se está seteando inactiva](https://github.com/cedarcode/mi_carrera/blob/master/db/data/subject_overrides.yml#L44-L45) esa materia, habría que cambiar esto.
