### ISSUE TITLE
Flexibilizar módulos de taller y extensión

### ISSUE THREAD

**Issue by santiagolmedo** [cedarcode/mi_carrera#498]
Según los programas de [MT](https://eva.fing.edu.uy/pluginfile.php/286747/mod_resource/content/1/UC_ModulosTallerComp.pdf) y [ME](https://eva.fing.edu.uy/pluginfile.php/286748/mod_resource/content/1/UC_ModulosExtensionComp.pdf) "_la cantidad de créditos de cada actividad específica será establecida de acuerdo a la dedicación horaria que ésta insuma, pero no deberá superar los 10 créditos (150 horas de trabajo). Esto quedará establecido al comienzo del módulo_". Aparte hay una restricción de no tener más de 18 créditos en cada uno.

Actualmente en micarrera solo te deja seleccionar un módulo de taller o extensión con una cantidad fija de créditos (5,4,3,2). Mi entendimiento es que los módulos tienen entre 1 y 10 créditos y eso se acuerda por cada módulo en específico. Capaz estaría bueno tener un dropdown que te deje seleccionar la cantidad de créditos del módulo?

En mi caso tengo un módulo de taller de 10 créditos y uno de 4. Para poder sumar los créditos tuve que poner módulos hasta que sumen 14 créditos como se ve 👇🏻 

<img width="850" alt="Screenshot 2024-07-13 at 7 29 17 PM" src="https://github.com/user-attachments/assets/71d4d542-c433-4c52-a469-a31766dd50d7">

<img width="810" alt="Screenshot 2024-07-16 at 3 15 17 PM" src="https://github.com/user-attachments/assets/e56913cb-c68c-4e2f-aa2c-b0a40366c4b7">

**Comment by santiagorodriguez96** [comment]
@santiagolmedo me alegra que hayas planteado esto! 

Esto es un 'known issue' en MiCarrera desde que la arrancamos más o menos 😕 De hecho yo también tengo un caso parecido al tuyo: aprobé una materia de módulo extensión de 7 créditos por lo que tuve que poner como aprobadas en MiCarrera los Módulos de Extensión A (4 créditos) y C (3 créditos)

![image](https://github.com/user-attachments/assets/6bbfdffe-63ea-4cdc-8355-06693cc464c9)

Francamente, entiendo que no es lo ideal pero no me parece tampoco una mala alternativa considerando la complejidad de hacerlo de una forma más representativa de la realidad.

Cómo vos decís, una de las opciones sería añadir funcionalidad para que los usuarios seleccionen la cantidad de créditos que obtuvieron del módulo de taller o extensión validando las restricciones de máximo 10 créditos por módulo y 18 en total. El tema es que eso implicaría un esfuerzo considerable ya que no tenemos hecho nada parecido, principalmente en términos de UI/UX.

Otra opción sería añadir varias materias de módulo de extensión, una por cantidad de créditos, tipo: `Módulo de Extensión - 10 créditos`, `Módulo de Extensión - 9 créditos`, etc. El problema con esto es que habría que agregar varias de cada una porque entiendo que podrías aprobar dos módulos de extensión de 4 créditos cada uno, por lo que tampoco convence mucho.

De nuevo, a mi me parece que la opción que manejamos hoy en día es la más simple y hasta donde sé permite cubrir todos los casos. Una cosa que también hemos pensado es hacer como una especie de `FAQ` en el cual pudiéramos documentar esta solución para que la gente entienda rápidamente cómo MiCarrera te permite registrar esos créditos actualmente.

Opiniones?

**Comment by santiagolmedo** [comment]
La verdad que después de leer la respuesta me convenció la opción actual. Me da curiosidad saber si esta es la forma que bedelías otorga los créditos actualmente pero supongo que sí porque son las materias que ellos tienen.

Como permite cubrir todos los casos y tampoco es un caso de uso muy frecuente me parece que la solución actual está bien. Gracias por la respuesta @santiagorodriguez96!

**Comment by santiagorodriguez96** [comment]
Genial! Cierro por lo pronto este issue entonces 🙂
